FROM maven:3.8.3-openjdk-17 AS build
COPY ./ /app
WORKDIR /app
RUN mvn clean package

FROM openjdk:17.0
RUN mkdir /app 
WORKDIR /app
COPY --from=build ./app/target/my-app-1.0-SNAPSHOT.jar /app
CMD java -jar my-app-1.0-SNAPSHOT.jar
